version: '3.2'

services:
  pritunl:
    build:
      context: .
      args:
        - MONGODB_VERSION=${MONGODB_VERSION}
    privileged: true
    ports:
      # - 80:80
      - '8443:443'
      - '1194:1194/udp'
      - '1194:1194/tcp'
    volumes:
      - './data/pritunl:/var/lib/pritunl'
      - './data/mongodb:/var/lib/mongodb'
    environment:
      - MONGODB_VERSION=${MONGODB_VERSION}

volumes:
  pritunl_data:
    driver: local
  pritunl_db:
    driver: local
